version: '3'

services:
  dev:
    build:
      dockerfile: dev.Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/mayavera.github.io/app
      - .env:/usr/src/mayavera.github.io/.env
